version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    reviewers:
      - "hashaambhatti"
    labels:
      - "dependencies"
      - "auto-update"
    allow:
      - dependency-type: "production"
      - dependency-type: "development"
    versioning-strategy: increase
