name: Dependency Updates

on:
  schedule:
    - cron: "0 0 * * 1"  # every Monday
  workflow_dispatch:

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: dependabot/fetch-metadata@v1
