name: Deployment Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: echo "Installing dependencies..." && sleep 2

      - name: Build App
        run: echo "Building the application..." && sleep 2

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Tests
        run: echo "Running tests..." && sleep 2

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Simulate Deployment
        run: echo "Deploying application to dummy server..." && sleep 2

      - name: Deployment Complete
        run: echo "✅ Deployment successful!"
