name: Task 7 - Custom Workflow

on:
  push:
    branches:
      - main

jobs:
  motivate:
    runs-on: ubuntu-latest
    steps:
      - name: Show Custom Message
        run: echo "Keep going! Code pushed successfully!"
